### ISSUE TITLE
Use stable release of slevomat/coding-standard

### ISSUE THREAD

**Issue by alcaeus** [doctrine/coding-standard#140]
This is a release blocker for 7.0: currently we require a dev-master commit of slevomat/coding-standard. This needs to be changed to a stable release before releasing 7.0.

**Comment by kukulich** [comment]
I was waiting for new release of PHPCS itself because of array functions support. Version 3.5.3 was released today, so I just need to write release notes for Slevomat CS and make the release :) This week for sure.

**Comment by alcaeus** [comment]
No worries - this issue is mainly here to block our automatic release tool: it refuses to create a release for a milestone with open issues. We've previously had to think of it and I'd like to have some insurance. Your release is ready when it's ready, we have some more things to take care of for 7.0 anyways.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/releases/tag/6.0.0

**Comment by carusogabriel** [comment]
Fixed via #144.
