### ISSUE TITLE
PSR-12 integration 

### ISSUE THREAD

**Issue by Alig96** [doctrine/coding-standard#141]
Since PSR-2 has been [deprecated](https://www.php-fig.org/psr/psr-2/) are there any plans change the ruleset base to PSR-12 or integrate any of the [new/changed](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-12-extended-coding-style-guide-meta.md#5-changelog-from-psr-2) features from the [ruleset](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR12/ruleset.xml)?

**Comment by alcaeus** [comment]
Yes, this is on our list. It most likely won't make it into 7.0, but we will definitely switch to PSR-12 as base.

**Comment by Alig96** [comment]
Awesome, thanks, looking forward to the update.
