### ISSUE TITLE
Add SlevomatCodingStandard.Functions.StrictCall

### ISSUE THREAD

**Issue by vladyslavstartsev** [doctrine/coding-standard#172]
I know that mostly this is checked by phpstan/psalm, but I think it will be good to double check this on phpcs level

**Comment by carusogabriel** [comment]
@vladyslavstartsev Sure, let's open a PR for that.

Could you do it?

**Comment by vladyslavstartsev** [comment]
@carusogabriel :facepalm:  this is not already released, it will be when `slevomat/coding-standard` 6.3.0 will be done

**Comment by kukulich** [comment]
I want to write one more sniff and then release 6.3.0.
