### ISSUE TITLE
Consider dropping auto fix of `SlevomatCodingStandard.Classes.ClassConstantVisibility`

### ISSUE THREAD

**Issue by BackEndTea** [doctrine/coding-standard#261]
Since the auto fixer for this rule sets the visibility to public, this may cause constants to get more visibility then really needed.

If they aren't auto fixed, the problem becomes more 'in your face', requiring you to consider what the exact visibility is that you need.

**Comment by derrabus** [comment]
> Since the auto fixer for this rule sets the visibility to public, this may cause constants to get more visibility then really needed.

No, constants without a visibility modifier have always been public. The auto-fixer is correct.

**Comment by BackEndTea** [comment]
> No, constants without a visibility modifier have always been public. The auto-fixer is correct.

True, they were public before. My problem is that some times these constants should have been private or protected.

**Comment by derrabus** [comment]
But how does removing the auto-fixer solve that problem for you?

**Comment by derrabus** [comment]
I'd like to close this issue as "won't fix".

On PHP versions that support visibility modifiers for constants, it is reasonable to enforce them. The current fixer implements the safest way forward. On classes where you don't want the fixer to be executed, you can ignore the corresponding sniff. If we just deactivted the fixer while keeping the sniff, you would need to do that anyway.

**Comment by beberlei** [comment]
You can just disable this rule in your project:

```xml
    <rule ref="Doctrine">
        <exclude name="SlevomatCodingStandard.Classes.ClassConstantVisibility" />
   </rule>
```
