### ISSUE TITLE
suggestion: a good readme

### ISSUE THREAD

**Issue by shaunthegeek** [doctrine/coding-standard#262]
such as:

- install
- usage

**Comment by derrabus** [comment]
suggestion: a good PR

such as:
* the README you would like to read

**Comment by greg0ire** [comment]
@sinkcup the current README has a link to the documentation, which shows installation and usage instructions: https://www.doctrine-project.org/projects/doctrine-coding-standard/en/8.2/reference/index.html#composer-project-dependency
