### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by simPod** [doctrine/coding-standard#301]
👋🏾 there has been a lot of new sniffs added and options tweaked. Could we maybe tag a new version? Currently, I have nothing on my mind I'd like to contribute on top what's already here in the near future.

Or is there something I can do to speed it up?

**Comment by greg0ire** [comment]
Sounds fine to me.

**Comment by greg0ire** [comment]
Let's start with a few merges up:
- https://github.com/doctrine/coding-standard/pull/302
-  https://github.com/doctrine/coding-standard/pull/303

**Comment by derrabus** [comment]
I've created draft PRs to test the new rules on the ORM codebase:

* doctrine/orm#10295
* doctrine/orm#10296

**Comment by derrabus** [comment]
I think we're good to go for 11.0.

**Comment by greg0ire** [comment]
On it!
