### ISSUE TITLE
Duplicate `RequireOneLineDocComment` in ruleset

### ISSUE THREAD

**Issue by tomudding** [doctrine/coding-standard#318]
Functionally this is not a problem, however, if the rule should ever be removed the other one may be left in the ruleset (and cause an headache when trying to figure out why nothing was affected).

First instance:
https://github.com/doctrine/coding-standard/blob/db39894b01cf5610a939387a1b79e2ae9dd85065/lib/Doctrine/ruleset.xml#L255-L256

Second instance:
https://github.com/doctrine/coding-standard/blob/db39894b01cf5610a939387a1b79e2ae9dd85065/lib/Doctrine/ruleset.xml#L493-L494

**Comment by greg0ire** [comment]
Oh wow well spotted… can you please send a merge request?
